### PR TITLE
Add idea: Dhall language server

### LINKED ISSUE #90: idea sketch : language server for dhall
From http://www.haskellforall.com/2019/01/dhall-year-in-review-2018-2019.html

> Editor support
>
> Another thing Dhall is missing compared to YAML is widespread editor support. This is why another one of my goals for this year is to create a Dhall language server so that any editor that supports the language server protocol (basically all of them) would get Dhall support for free.

So, use `haskell-lsp` to construct a LSP server for dhall.  Similar to the ones for

- https://github.com/haskell/haskell-ide-engine
- https://github.com/elm-tooling/elm-language-server
- https://github.com/domenkozar/hnix-lsp

Which are all based on that library.

cc @Gabriel439

### PR DESCRIPTION
**Pull request by Gabriella439**
Fixes #90

### CODE REVIEW

**Comment by Gabriella439** [comment]
Note that I'm currently asking @PanAeon (the person currently working on the language server) if they want to comentor with me on this project

**Review by jaspervdj — APPROVED** [review]
This is excellent, thanks!  We'll wait with merging until we have more info on the mentoring then.

**Comment by Gabriella439** [comment]
@jaspervdj: So after checking with them it will be just me doing mentoring for this project, so this is ready to merge as is

**Comment by jaspervdj** [comment]
@Gabriel439 Ok, perfect, thanks!

**Pull request merged**
