### PR TITLE
Functional software architecture analysis

### PR DESCRIPTION
**Pull request by morgenthum**

### CODE REVIEW

**Comment by jaspervdj** [comment]
I think this proposal is currently a bit too open -- it should focus on a few specific measurements.  But I'm also not sure what sort of shape this project would take -- is this going to be an entirely new static analysis suite for Haskell or does it tie into one of the existing development tools?

**Comment by morgenthum** [comment]
It's going to be an entirely new static analysis suite! The project isn't about implementing metrics at all, it's about creating a fundamental library (type classes, types, monads or whatever needed) for metrics in general, not the metrics itself. One should be able to implement metric analyzers for any programming language. It would be nice to provide a reference implementation for Haskell using the GHC-API to analyze code and extract metrics. Basic example metrics could be ACD (average component dependency) and those described in the linked document. The result should be a description containing the result, in a standard file format like xml, yaml or json, which could be used for different purposes, like visualization or checking against thresholds during deployments and such things.

**Comment by jaspervdj** [comment]
I read through the paper and I'm still not sure if it is doable for a student to do a project like this in a summer.  I think we could have higher confidence in this if we got a mentor who has experience with the GHC API, but I also suspect these folks would rather mentor GHC related projects?

**Comment by morgenthum** [comment]
Ok, it seems we won't add this idea. It's ok for me. :)

**Pull request closed without merging**
