### PR TITLE
Add idea for haskell-ide-engine

### PR DESCRIPTION
**Pull request by alanz**
Please do not merge yet

### CODE REVIEW

**Comment by alanz** [comment]
Ping @saurabhnanda @wz1000 
Comments please

**Comment by jaspervdj** [comment]
It will be good to have another HIE project 👍

**Comment by alanz** [comment]
This will do for a start.  Merge when convenient.

**Comment by jaspervdj** [comment]
@alanz Can you add a "Difficulty" as well as discussed in #23?

**Comment by nponeccop** [comment]
- As can be seen at https://github.com/alanz/summer-of-haskell/blob/7cbc7c85547f80fb837257aada88ee9eaa55a693/content/ideas/haskell-ide-engine.md markdown is broken - use space-indented dashes instead of multiple dashes
- The last `new-build` feature is a duplicate of "add more build types"

**Comment by saurabhnanda** [comment]
@alanz @wz1000 what level of detail are we expecting in proposals from students? For a student who's not well-versed with the HIE code, it seems that a lot of effort is required at the student's end to first understand the problem & existing code, to be able to propose a solution. I'm wondering if building a proposal itself, would end-up becoming a mini-project?

**Comment by jaspervdj** [comment]
@saurabhnanda Writing a good proposal is a bit of a mini-project.  For us, it's the only way to judge students and decide which ones we accept, so it's not a bad thing if some work is involved.

**Comment by gwils** [comment]
@alanz Please see https://github.com/alanz/summer-of-haskell/pull/1

**Comment by alanz** [comment]
I think this is ready for a merge now

**Pull request merged**
