### PR TITLE
New idea: ThreadScope large file handling

### PR DESCRIPTION
**Pull request by osa1**

### CODE REVIEW

**Comment by maoe** [comment]
Looks good to me. Should the difficulty be set to intermediate? The student needs to understand what various versions of GHC RTS do to address the bugs and also probably needs to do some hacky GTK programming to support lazy loading in GtkTreeView.

**Comment by jaspervdj** [comment]
@osa1 I also think this should be rated intermediate.  Other than that it looks good, this would definitely help the Haskell community!

**Comment by osa1** [comment]
Fair enough. Updated the difficulty.

**Comment by jaspervdj** [comment]
@osa1 I hope you would still be available for mentoring if this gets accepted for 2019?

**Comment by osa1** [comment]
@jaspervdj Thanks for merging! Currently there are no problems with me mentoring this project, but I'll let you know beforehand if for some reason I won't be able to mentor it.

**Pull request merged**
