### PR TITLE
New idea: Benchmarking graph libraries and optimising algebraic graphs 

### PR DESCRIPTION
**Pull request by nobrakal**
Made on an idea and with help of @snowleopard

### CODE REVIEW

**Comment by AndreasPK** [comment]
It seems a bit broad in scope to me.

At least more information about deliverables would be good. Otherwise misunderstandings in that regard are bound to happen.

> Develop a high-quality, automated and fair benchmarking suite for these libraries. The main goal is to help developers to choose easily the library that fits their project.

* A list of usecases for which there should be benchmarks would be good.
* What does automated mean in this context?
* When would a benchmark be considered fair?
* We all want high quality code. But what does that mean for this proposal?

> Implement missing algorithms and optimize existing ones on the basis of the developed benchmarking suite. Graph libraries are expected to provide some basic algorithms, but because Alga is so different from conventional graph representations most of these algorithms need to be designed from scratch.

* Again which algorithms?
* What happens if the student doesn't find a good design, given how new the approach is that seems like a possibility?

Overall to me it sounds like a interesting proposal. But it might be a bit much. Developing a Graph benchmark framework alone sounds like something that can easily be expanded to fill a SoC project given how tricky benchmarking can be.

**Comment by nobrakal** [comment]
Hi,

Thank you for your detailed feedback !

> * A list of usecases for which there should be benchmarks would be good.
> * What does automated mean in this context?
> * When would a benchmark be considered fair?

You are right, there was a lack of precision, so I have documented this in the [updated proposal](https://github.com/haskell-org/summer-of-haskell/pull/54/commits/cb95cf9a2a56693d7da2d5869f284954232ec347). 

> * We all want high quality code. But what does that mean for this proposal?

High-quality was just here to reflect the motivation to make a good code. Indeed, since it is difficult to make "high-quality" precise, I have dropped it.

> * Again which algorithms?

The project will mainly focus on the ones from the benchmarking suite.

> * What happens if the student doesn't find a good design, given how new the approach is that seems like a possibility?

Here the student will have the support of the library author and will share its difficulties to the Haskell community through a blog (I just added this in the proposal), so the student will certainly avoid any dead end.

>Overall to me it sounds like a interesting proposal. But it might be a bit much. Developing a Graph benchmark framework alone sounds like something that can easily be expanded to fill a SoC project given how tricky benchmarking can be.

@snowleopard and I think that 3 months are enough for both implementing the benchmarks and doing useful Alga optimisation. To put a time marker, I added:

`The aim is to complete the benchmarking suite before the mid-term evaluation.`

**Comment by jaspervdj** [comment]
This looks good to me.  There is a markdown issue though.  The rendered proposal can be seen here: <https://github.com/nobrakal/summer-of-haskell/blob/3bbef3e3f3304d741213c3f7056eef0c3e37c2c6/content/ideas/graphs.md>.  I think some of the paragraphs need to be indented more because they're part of the bullet list...

**Comment by nobrakal** [comment]
Hi, thank you for the comment :)
Indeed, there was some sentences poorly positioned, I have corrected the ones I found (and added a numbered list for clarity).

**Comment by snowleopard** [comment]
@jaspervdj I was just approached by another student interested in this project. I'm not sure about the right protocol with student-proposed projects: is it open for any student or only for the proposer?

In any case, I think it is worth adding a note that this project is proposed by @nobrakal who intends to apply to work on it as part of GSoC.

@nobrakal Will you do a pull request?

**Comment by jaspervdj** [comment]
Projects on our website should be open for all students to apply, and we should help all students writing a proposal.  In the end we should choose the best proposal for a given project in a fair way.  I think being the person who originally wrote the project idea already gives you a nice advantage, but that doesn't mean we should turn down other people.

**Comment by snowleopard** [comment]
@jaspervdj Many thanks for clarifying! This sounds fair. I'll let other students know they are free to apply.

I guess we don't need to add any note to the project idea in this case.

**Pull request merged**
