### PR TITLE
Add a project on Hadrian

### PR DESCRIPTION
**Pull request by snowleopard**
@ndmitchell @alpmestan Please suggest improvements. (Alp: Neil and I had a chat today and thought that this could be a nice GSoC project. I hope you don't mind to be a mentor.)

@jaspervdj In the end I decided to go with a Hadrian project (instead of algebraic graphs), since it has a more direct benefit for the whole community.

### CODE REVIEW

**Comment by alpmestan** [comment]
Good idea!

**Comment by ndmitchell** [comment]
I think the description makes it sound harder than it is. We already have at least 10 ideas of how to start tackling the project, so it's not as difficult as scrambling around in the dust for leads, we have absolutely loads of them! Perhaps put something along those lines in it.

**Comment by snowleopard** [comment]
@ndmitchell Could you suggest a few specific ideas? I have some rather vagues ones, but I hesitate adding them, because they might tempt a potential student to skip the important "do profiling first" step.

**Comment by ndmitchell** [comment]
@snowleopard good point... I just don't want it to sound like we're throwing them against a problem we have no idea to solve, which is definitely not the case. Perhaps adding near the bottom:

> We have already identified several promising possibilities for optimisation, and several profiling techniques that are certain to uncover others, so there are plenty of paths to follow.

**Comment by snowleopard** [comment]
@ndmitchell Sounds good! Done.

**Comment by jaspervdj** [comment]
Thanks all!!

**Pull request merged**
