### PR TITLE
Add "finish cabal new-build" idea from cabal wiki

### PR DESCRIPTION
**Pull request by gwils**
How does this look @ezyang @23Skidoo @hvr ?
Are any of you willing to mentor this project?

### CODE REVIEW

**Comment by ezyang** [comment]
This task seems to big. Here's an alternate proposal: rip out all of the old build/sandbox code from cabal-install, and rename the new-* commands so that they're the old commands. See what breaks.

I've actually been semi-thinking that what might make the most sense is for us to do a rebrand of cabal-install at the same time. Maybe `cbl` or `cab`.

**Comment by gwils** [comment]
Hi Edward. I'm interested in digging further into what you've just said.

What do you mean by "see what breaks"? I'm sure there are tests that will fail, but do you mean to try using the modified cabal out in the wild as well?

Is this just a throw-away smoke test to see what breaks and inform further development, or would it be intended to be merged?

Is there any chance you could write up that proposal in a pull request like this one? Or if you can sketch out enough dot points for me I can write it up.

**Comment by gbaz** [comment]
@ezyang well if `cabal new-haddock` doesn't work, we know it wouldn't work, right?

What if the proposal simply said "of the work that needs to be done, it is not expected that a single student can complete it all over a summer. A proposal containing any reasonable subset would be welcomed."?

**Comment by ezyang** [comment]
So, the overarching principle is, at some point, cabal-install is going to have to rip the band-aid off and make it so `cabal build` does the all of the "new" stuff.

One way to do this is to bite the bullet and just delete all of the old stuff and move the new commands to the alias. Another is to release a new executable (which I will provisionally call `cbl`) which has jettisoned all of the legacy stuff; this gives you the extra option of keeping the old `cabal` codebase on life support until know one cares about it any more.

@gbaz's suggestion seems reasonable too. Instead of "all of the remaining new-build work", just say something like, "make new-haddock work."

**Comment by gwils** [comment]
How does that look?

**Comment by hvr** [comment]
I'm happy to co-mentor this one;
Fwiw, I'd change the difficulty to "intermediate/advanced" depending on which subset is picked by the student. Many of the smaller (and yet important) subtasks are definitely not "advanced".

**Comment by gwils** [comment]
Fair call.

**Comment by jaspervdj** [comment]
👍  Thanks!

**Comment by 23Skidoo** [comment]
@gwils Thanks for doing this!

**Pull request merged**
