### PR TITLE
improve calligraphy

### PR DESCRIPTION
**Pull request by lsmor**
As discussed [here](https://discourse.haskell.org/t/gsoc-2023-call-for-ideas/5606/10) I am willing to mentor this project, but I have very little experience in that. Which expectations do you have for mentors? Should they be professional haskellers? I am mostly a hobbist. 

Best Regards,
Luis

### CODE REVIEW

**Review by jaspervdj — APPROVED** [review]

**Comment by jaspervdj** [comment]
@lsmor there's no requirement to be a professional Haskeller -- just the willingness to answer questions from the student/contributor and help guide them a bit.  This obviously depends on the level of any student who applies, and you'll get to be part of that decision as well.  I would say mentors typically spent half an hour to an hour a week on this.

**Comment by lsmor** [comment]
@jaspervdj Then, I am willing to be a mentor :). Let me know what do you think about the proposal and if it is too hard or could be improved.

**Comment by jaspervdj** [comment]
I think the difficulty can be downgraded to "Medium", looking at past GSoC projects, "Hard" is usually reserved for e.g. GHC-related projects.  Other than that it looks fine to me!

**Comment by jaspervdj** [comment]
@lsmor it looks like the choice for project size should be binary -- 175 or 350 hours, so I've turned this into `350 hours, possibly 175 for an experienced contributor` in f067ff680716943bf25a398bcaaaadd74b83e001, feel free to still send follow-up changes though.  Can you also send me a quick email at m at jaspervdj.be so I have your email on file to eventually invite you to the GSoC dashboard (when it opens and if Haskell gets accepted this year).

**Pull request merged**
