### PR TITLE
Add OpenTelemetry idea

### PR DESCRIPTION
**Pull request by ethercrow**
A proposal to improve the opentelemetry library and have a better performance profiling and observability story for Haskell.

Please tell me if something is not clear or I should add more details, it's hard to know if this document is readable for someone not familiar with OpenTelemetry or something similar.

### CODE REVIEW

**Comment by jaspervdj** [comment]
How does this relate to [ekg](https://github.com/tibbe/ekg)?  Would there be a way to implement GC statistics in OpenTelemetry as well?  This looks pretty interesting but would be better with a backup mentor as well.

**Comment by ethercrow** [comment]
> How does this relate to ekg?

I didn't yet get to implementing the Metrics portion of OpenTelemetry, but superficially it looks similar to EKG. The Tracing portion that I've been using so far is definitely not something that EKG helps you with.

> Would there be a way to implement GC statistics in OpenTelemetry as well?

I think it would fit very well with the Metrics API.

> This looks pretty interesting but would be better with a backup mentor as well.

Sure, I'd be happy to have another mentor for this.

**Comment by ethercrow** [comment]
@synthorchid @jonasp @qnikst @erthalion are you interested in mentoring this?

**Comment by qnikst** [comment]
As far as I understand open telemetry it's another dimension of the metric tools comparing to ekg. `ekg` and `prometheus` works as metrics gathering application, i.e. when application sets its specific metrics and we gather statistical information for later analysis. Such metrics doesn't give us much information about each particular thread behaviour and timings, instead it gives us statistics as a whole, so we can understand if application or it's module works well or not.

Opentelemetry can work as a task tracer i.e. it gives information about timings of each thread (and it can add tags to data in order by provide better analyses. With this kind of metrics we can understand where we are spending time and what part of the application needs improving. In this sense open telemetry is closer to eventlogs, ghc-events-analyze and ability to stream event log.

The big difference in that opentelemetry is an open format so we reuse existing tools and not reimplement our own. But it's may be possible that we can reuse eventlog functionality for maintaining telemetry.

I may be interested in co-mentoring this project, but I'm not sure about my availability during this summer.

**Comment by erthalion** [comment]
> are you interested in mentoring this?

@ethercrow  Not entirely sure about the process of mentoring and such, but I'm ready to spend some time to help with this.

**Comment by jaspervdj** [comment]
I'm gonna go ahead and merge this to get the ideas page ready in preparation for our GSoC application; but please do add a back-up mentor; it's very helpful when you are e.g. traveling during the summer and the student has one or two simple questions.

**Comment by synthorchid** [comment]
@ethercrow same as @erthalion I am not sure about the whole mentoring concept but I am generally happy to help.

**Comment by jaspervdj** [comment]
@ethercrow I don't have your email address.  Can you shoot me a quick email on m at jaspervdj dot be so I can get you added to the GSoC dashboard?

**Pull request merged**
