### PR TITLE
Adds idea - 'A library for in-memory data analysis in Haskell'

### PR DESCRIPTION
**Pull request by gagandeepb**

### CODE REVIEW

**Comment by jaspervdj** [comment]
Pinging @ocramz for review

**Comment by ocramz** [comment]
We've already been iterating over this together with @gagandeepb , so 👍 from me. I am also seeking feedback from other community members regarding the scope and merit of the proposal.

**Comment by ocramz** [comment]
@jaspervdj since the GSoC application deadline is March 27, what else is needed for merging this?

**Comment by jaspervdj** [comment]
I've merged it but:

1. If a student successfully applies for a proposal based on this idea, we will need a back-up mentor as well.

2. Just FYI, it's not really necessary for ideas to be merged.  The page is just to inspire students, they still need to submit their own proposal to the Google Summer of Code dashboard, where the proposals will be judged on their own merit, regardless of whether or not it was based on an existing idea.

**Pull request merged**
