### PR TITLE
Add the Hackage package collections project idea.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Plus some tweaks to the new-build project idea description.

/cc @hvr @dcoutts

### CODE REVIEW

**Comment by jaspervdj** [comment]
The tweaks look good, but the other project seems close to impossible to pull of in a summer.  I'll wait for @hvr or @dcoutts to weigh in though.

**Comment by 23Skidoo** [comment]
Yep, I mentioned in the last paragraph that we don't expect this to result in a full implementation. I can make that more prominent if you want.

**Comment by hvr** [comment]
@jaspervdj  I already expressed my reservations to @23Skidoo, and that's reflected in the wording of the proposal text. This puts this project into a different category than the other ideas proposed for this year, as it's likely the majority of it will be design work, and writing up a detailed specification to integrate into the existing status quo (TUF, cabal-spec, hackage api, backward-compat(!), etc), and then (time permitting) implement the minimum viable subset of it.

**Comment by 23Skidoo** [comment]
The design process can be combined with writing better documentation -- which is a nice way to learn about new stuff. For example, the documentation for `hackage-security` could really be improved.

**Comment by jaspervdj** [comment]
In that case, we might also need to hold off until we know whether or not we are accepted in GSoC, and whether or not we will find sponsors to support additional slots.

GSoC explicitly forbids projects that are not mainly about "writing code", so writing designs or documentation doesn't really fit.

This is a bit unfortunate, since I would also really like to have a project which focuses exclusively on improving documentation of commonly used libraries (base in particular, and things like vector, containers, text...).  I hope we can do that (and maybe this, if it fits the bill) as additional slots outside of GSoC.

**Comment by 23Skidoo** [comment]
BTW, if there will be additional non-GSoC slots, I have another "documentation" project idea in mind: writing down an updated [reference specification](https://www.haskell.org/cabal/proposal/pkg-spec.pdf) for the `.cabal` file format and the `Cabal <-> GHC` interface. This can be expanded with further tasks like rewriting the manual, adding a new tutorial, and creating a new website.

**Comment by jaspervdj** [comment]
I'm closing this as I'm cleanup issues for the 2019 GSoC.  Feel free to resubmit this idea if it still relevant!

**Pull request closed without merging**
