### PR TITLE
Idea: quickcheck APIs.

### PR DESCRIPTION
**Pull request by jkarni**

### CODE REVIEW

**Comment by jaspervdj** [comment]
This looks alright.

I'm wondering if any of the existing swagger libraries on hackage could provide a good starting point?  Perhaps through a combination of `servant-client` and `servant-swagger`?  Could you add some more info on that?

**Comment by jkarni** [comment]
`servant-quickcheck` (mentioned) provides everything you need once you have a `servant` API type, so the main thing that's needed is `Swagger -> ServantAPI` (`servant-swagger` goes the other way). That exists in Java as part of the official swagger tool, but is a very big pain to use and package, so we really should do it anew. Brendan Hay has some work in that direction (including indeed other API description languages), but it isn't yet public, much less on hackage.

Should I add some version of all that to the idea proposal?

**Comment by jkarni** [comment]
@jaspervdj added some more info on related work.

**Comment by jaspervdj** [comment]
Looks good now, thanks for updating this!  The only remaining thing it needs is a bunch of links at the bottom that link to the projects so students can check those out easily.  Could you add that as well?

**Comment by jkarni** [comment]
done!

**Comment by jaspervdj** [comment]
Thanks!

**Pull request merged**
