### PR TITLE
Idea proposal: hacking on GHC

### PR DESCRIPTION
**Pull request by goldfirere**
[Rendered](https://github.com/goldfirere/summer-of-haskell/blob/patch-1/content/ideas/ghc-type-system.md)

### CODE REVIEW

**Comment by jaspervdj** [comment]
Hey @goldfirere, thanks for the suggestion!

I would love to have a GHC type system-related proposal in there.  We had a linear types project last year and this would make for a nice blend of practice and theory.

However, I think the proposal should be more much more concrete.  I don't think it's feasible for students to come up with an extension _and_ a solid theoretic base for it, so I would double down on the quantified class constraints, add some more context about that in the proposal.  At the end, we can then have one short sentence that other projects are also considered and link to the tickets.  This is really implied anyway since students are free to propose their own projects loosely based on the ideas on our page.

Does that make sense to you?  Feel free to disagree :-)

**Comment by gwils** [comment]
Thanks for the suggestion :)

I agree with @jaspervdj - this looks great, but I would prefer this umbrella idea be made into a more concrete idea (or ideas?).

What do you think @goldfirere ?

**Comment by goldfirere** [comment]
I think these are very reasonable suggestions. Will do. But not today -- grades are due! :)

**Comment by goldfirere** [comment]
OK. I've revised. How does it look now? Thanks!

**Comment by gwils** [comment]
Looks great to me! I reckon this should be merged. @jaspervdj ?

**Comment by mrkgnao** [comment]
I would be interested in applying to SoH with the goal of working on Dependent Haskell, but I don't think relocating to Philadelphia is going to be possible for me. 

@goldfirere, would you be okay with mentoring remote candidates?

**Comment by goldfirere** [comment]
@mrkgnao yes, absolutely. I'll clarify that.

**Comment by jaspervdj** [comment]
Thanks, looking good!

**Comment by mrkgnao** [comment]
@goldfirere thanks for clearing that up!

**Pull request merged**
