### PR TITLE
Add persistent/postgres binary backend

### PR DESCRIPTION
**Pull request by erikd**
Would really like to be able to add @snoyberg (Michael Snoyman, Persistent) and @nikita-volkov (Nikita Volkov Hasql/postgres-binary) as mentors if they agree.

### CODE REVIEW

**Comment by gwils** [comment]
Please add a difficulty estimate (#23)
So far we've been using beginner/intermediate/advanced for these estimates.

This looks good to me otherwise 👍

**Comment by erikd** [comment]
Difficulty added.

**Comment by snoyberg** [comment]
I'm not sure I'm the best person to mentor it, as I've been away from the day to day maintenance of persistent for a while. But if no one better suited is available, I can do it. Thanks for the ping.

**Comment by erikd** [comment]
@snoyberg If you can recommend someone else, that would also work.

**Comment by nikita-volkov** [comment]
Sure! I'll be able to consult on my part.

**Comment by gwils** [comment]
This looks ready to merge to me. What do you reckon @jaspervdj?

**Comment by erikd** [comment]
Since both @snoyberg and @nikita-volkov have agreed, should I add them as mentors?

**Comment by MaxGabriel** [comment]
I've been doing regular work on Persistent and I'd be happy to help on this as well.

**Comment by jaspervdj** [comment]
@MaxGabriel Feel free to send a PR to add yourself as mentor. :-)

**Pull request merged**
