### PR TITLE
Haskell Program Analysis using GHC Source Plugins idea

### PR DESCRIPTION
**Pull request by mpickering**

### CODE REVIEW

**Comment by jaspervdj** [comment]
This looks good to me but also needs a mentor.  Perhaps @nboldi is interested?

**Comment by wz1000** [comment]
I think more source analysis tools are a very good thing. The information the extended plugin API provides is similar to the information HIE can provide its plugins, so integrating the analysis into HIE could also be easy if a suitable library interface is provided.

**Comment by nboldi** [comment]
@jaspervdj Yes, I think it is a great idea and I would be glad to help.

**Comment by mpickering** [comment]
I think [the idea](https://github.com/ghc-proposals/ghc-proposals/pull/107#issuecomment-363377934) that @ocharles has would also be a good size for a project. If he would be willing to be a mentor as well? I think there is already some code for it as well to get someone going.

**Comment by ocharles** [comment]
I would be happy to try and mentor that, though I have zero (* ok, 0.0001%) experience actually doing GHC hacking. But I'm sure I can learn that

**Comment by jaspervdj** [comment]
Thanks!

**Comment by jaspervdj** [comment]
Added @ocharles and @nboldi as possible mentors.

**Pull request merged**
