### PR TITLE
Add persistent perf idea

### PR DESCRIPTION
**Pull request by psibi**
Michael has agreed to be a mentor if nobody else steps up.

### CODE REVIEW

**Comment by jaspervdj** [comment]
Sounds good, but I would like to have a mentor who has some sort of idea where the problems are.  Perhaps @gregwebs?

Is there a lot of low hanging fruit in the different libraries?  If there's not, it might be better to focus on a specific backend (e.g. postgresql).

Where do you envision the work would go?  I can imagine it could be any of the following:

- `persistent`
- `persistent-postgresql`
- `postgresql-simple`

**Comment by psibi** [comment]
> Is there a lot of low hanging fruit in the different libraries? If there's not, it might be better to focus on a specific backend (e.g. postgresql).

My guess would be yes. Also each backend communicates with the base library `persistent`. So, if you do a `perf` improvement in `persistent`, it's likely to affect all the backends.

> Where do you envision the work would go? I can imagine it could be any of the following:

In my recent benchmarks of `persistent-sqlite` (which doesn't have dependencies on any other haskell DB bindings), it performed very badly. So, my guess is that perf improvement would likely go to `persistent` related libraries. But in case of other backends like postgresql, it may also go to `postgresql-simple` too.

> Sounds good, but I would like to have a mentor who has some sort of idea where the problems are. Perhaps @gregwebs?

Sure, why not. That's why I had the `??` sign along with Michael's name. Infact, Michael agreed to be a mentor if nobody else steps up.

**Comment by gregwebs** [comment]
Sorry, I don't have bandwidth to be a mentor, but I am willing to answer questions about what the internals do.

Also, I don't actually have insight to performance bottlenecks. Unfortunately persistent has always worked well enough for me (actually persistent-mongoDB used to be extremely slow, but the issue in the mongoDB driver was found and addressed).

**Comment by jaspervdj** [comment]
@psibi Do you want to flesh out this proposal a bit more?  I think we should at least link to some concrete benchmark results rather than a repository, if possible.

**Comment by jaspervdj** [comment]
I'm closing this as I'm cleanup up the website in preparation for 2019, but feel free to resubmit this as a new PR/issue when I send out the call for ideas 2019 soon :-)

**Pull request closed without merging**
