### PR TITLE
New Idea: Implement Automatic Differentiation in the Accelerate libraries

### PR DESCRIPTION
**Pull request by alex404**
Here's a project proposal that Trevor McDonell, Edward Kmett, and I have been putting together for getting automatic differentation into `accelerate`. This project could be quite challenging, but with @tmcdonell and @ekmett 's expertise I think it should be doable and rewarding.

### CODE REVIEW

**Comment by jaspervdj** [comment]
@alex404 Oh this is interesting!

There are some HTML comments in the markdown -- are these supposed to be there or should they be removed?

**Comment by tmcdonell** [comment]
I deleted the HTML comments, those were just from previous revisions as we worked on the proposal (:

**Comment by jaspervdj** [comment]
Nice, thanks!

**Comment by alang9** [comment]
@alex404 @ekmett @tmcdonell Is the task to allow ad to differentiate things like `Forward (Exp Double) -> Foward (Exp Double)` or things like `Acc (Vector (Forward Double)) -> Acc (Scalar (Forward Double))`?

The second appears much more difficult than the first

**Comment by tmcdonell** [comment]
@alang9 (ideally) the second, though I agree that is more difficult. Fritz Henglein and Gabriele Keller have been working on this recently and I think have a very nice solution, so I am going to bring them on board.

**Comment by alang9** [comment]
@tmcdonell I'm interested about this. Is there a paper I can read?

**Comment by tmcdonell** [comment]
@alang9 they don't have a paper out yet, but it is currently in the final stages of being written. Thanks for reminding me to add them to the proposal! (#64)

**Pull request merged**
